const robot = require('robot-js')

module.exports = {
  'PrintScreen': robot.KEY_PRINT,
  'Pause': robot.KEY_PAUSE,
  
  'NumpadAdd': robot.KEY_ADD,
  'NumpadSubtract': robot.KEY_SUBTRACT,
  'NumpadEqual': robot.KEY_EQUAL,
  'NumpadMultiply': robot.KEY_MULTIPLY,
  'NumpadDivide': robot.KEY_DIVIDE,

  'NumpadEnter': robot.KEY_RETURN,
  'Numpad0': robot.KEY_NUM0,
  'Numpad1': robot.KEY_NUM1,
  'Numpad2': robot.KEY_NUM2,
  'Numpad3': robot.KEY_NUM3,
  'Numpad4': robot.KEY_NUM4,
  'Numpad5': robot.KEY_NUM5,
  'Numpad6': robot.KEY_NUM6,
  'Numpad7': robot.KEY_NUM7,
  'Numpad8': robot.KEY_NUM8,
  'Numpad9': robot.KEY_NUM9,
  'NumpadDecimal': robot.KEY_DECIMAL,

  'MetaLeft': robot.KEY_LSYSTEM,
  'MetaRight': robot.KEY_RSYSTEM,
  'OSLeft': robot.KEY_LSYSTEM,
  'OSRight': robot.KEY_RSYSTEM,

  'Semicolon': robot.KEY_SEMICOLON,
  'Quote': robot.KEY_QUOTE,
  'Comma': robot.KEY_COMMA,
  'Slash': robot.KEY_SLASH,
  'Period': robot.KEY_PERIOD,
  'Backquote': robot.KEY_GRAVE,
  'Backslash': robot.KEY_BACKSLASH,
  
  'Divide': robot.KEY_DIVIDE,
  'Multiply': robot.KEY_MULTIPLY,
  'Insert': robot.KEY_INSERT,
  'Delete': robot.KEY_DELETE,
  'Home': robot.KEY_HOME,
  'End': robot.KEY_END,
  'PageUp': robot.KEY_PAGE_UP,
  'PageDown': robot.KEY_PAGE_DOWN,

  'CapsLock': robot.KEY_CAPS_LOCK,
  'ScrollLock': robot.KEY_SCROLL_LOCK,
  'NumLock': robot.KEY_NUM_LOCK,

  'ShiftLeft': robot.KEY_LSHIFT,
  'ShiftRight': robot.KEY_RSHIFT,

  'BracketLeft': robot.KEY_LBRACKET,
  'BracketRight': robot.KEY_RBRACKET,

  'ControlRight': robot.KEY_RCONTROL,
  'ControlLeft': robot.KEY_LCONTROL,

  'AltRight': robot.KEY_RALT,
  'AltLeft': robot.KEY_LALT,

  'Add': robot.KEY_ADD,
  'Minus': robot.KEY_SUBTRACT,
  'Equal': robot.KEY_EQUAL,
  'Period': robot.KEY_PERIOD,

  'Digit0': robot.KEY_0,
  'Digit1': robot.KEY_1,
  'Digit2': robot.KEY_2,
  'Digit3': robot.KEY_3,
  'Digit4': robot.KEY_4,
  'Digit5': robot.KEY_5,
  'Digit6': robot.KEY_6,
  'Digit7': robot.KEY_7,
  'Digit8': robot.KEY_8,
  'Digit9': robot.KEY_9,

  'ArrowUp': robot.KEY_UP,
  'ArrowDown': robot.KEY_DOWN,
  'ArrowLeft': robot.KEY_LEFT,
  'ArrowRight': robot.KEY_RIGHT,

  'Enter': robot.KEY_ENTER,
  'Escape': robot.KEY_ESCAPE,
  'Space': robot.KEY_SPACE,
  'Tab': robot.KEY_TAB,
  'Bakspace': robot.KEY_BACKSPACE,

  'KeyA': robot.KEY_A,
  'KeyB': robot.KEY_B,
  'KeyC': robot.KEY_C,
  'KeyD': robot.KEY_D,
  'KeyE': robot.KEY_E,
  'KeyF': robot.KEY_F,
  'KeyG': robot.KEY_G,
  'KeyH': robot.KEY_H,
  'KeyI': robot.KEY_I,
  'KeyJ': robot.KEY_J,
  'KeyK': robot.KEY_K,
  'KeyL': robot.KEY_L,
  'KeyM': robot.KEY_M,
  'KeyN': robot.KEY_N,
  'KeyO': robot.KEY_O,
  'KeyP': robot.KEY_P,
  'KeyQ': robot.KEY_Q,
  'KeyR': robot.KEY_R,
  'KeyS': robot.KEY_S,
  'KeyT': robot.KEY_T,
  'KeyU': robot.KEY_U,
  'KeyV': robot.KEY_V,
  'KeyW': robot.KEY_W,
  'KeyX': robot.KEY_X,
  'KeyY': robot.KEY_Y,
  'KeyZ': robot.KEY_Z,

  'F1': robot.KEY_F1,
  'F2': robot.KEY_F2,
  'F3': robot.KEY_F3,
  'F4': robot.KEY_F4,
  'F5': robot.KEY_F5,
  'F6': robot.KEY_F6,
  'F7': robot.KEY_F7,
  'F8': robot.KEY_F8,
  'F9': robot.KEY_F9,
  'F10': robot.KEY_F10,
  'F11': robot.KEY_F11,
  'F12': robot.KEY_F12,
}
